before_install:
 - git clone --recursive -b osxfuse-2 git://github.com/osxfuse/osxfuse.git osxfuse
 - cd osxfuse
 - ./build.sh -t dist
 - brew install glib libevent libxml2 openssl libmagic
language: objective-c
compiler:
  - gcc
  - clang
script: 
  - ./autogen.sh
  - ./configure --enable-test-apps
  - make
notifications:
  irc:
    channels:
      - "irc.freenode.org#riofs"
    on_success: always
    on_failure: always
