before_install:
 - brew install automake autoconf libtool pkgconfig glib libevent libxml2 openssl libmagic
language: objective-c
compiler:
  - gcc
  - clang
script: 
  - ./autogen.sh
  - ./configure --enable-test-apps
  - make
notifications:
  irc:
    channels:
      - "irc.freenode.org#riofs"
    on_success: always
    on_failure: always
