before_install:
  - brew install https://raw.github.com/skoobe/riofs/master/riofs.rb
language: objective-c
compiler:
  - gcc
  - clang
script: 
  - ./autogen.sh
  - ./configure --enable-test-apps
  - make
notifications:
  irc:
    channels:
      - "irc.freenode.org#riofs"
    on_success: always
    on_failure: always
