before_install:
 - sudo apt-get update -qq
 - sudo apt-get install -qq libglib2.0-dev libfuse-dev libxml2-dev libevent-dev libssl-dev
language: c
compiler:
  - gcc
script: ./autogen.sh && ./configure && make
